### ISSUE TITLE
V1.0.1 Patch

### ISSUE THREAD

**Issue by gonzalespaulb** [gonzalespaulb/Pokemon-App#176]
## V 1.0.1
- [x] #177
- [x]  #178
- [x]  #179 
- [x] #180 
- [x] #181 
- [x] #182 
- [x] #183 
- [x] #184
- [x] #192 
- [x] #193 
- [x] #196 
- [x] #201
- [x] #204 
- [x] #209
- [x] #207

**Comment by krferrell** [comment]
## V 1.0.1
- [ ] #177
- [ ]  #178
- [ ]  #179 
- [ ] #180 
- [ ] #181 
- [ ] #182 
- [ ] #183 
- [ ] #184
